project:
  type: website
  output-dir: docs
website:
  title: "M. Ahmed's Health Data Science Career Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

